version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: install deps
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run lint
          command: npm run lint

workflows:
  build-and-test:
    jobs:
      - test-node
      